name: finance-mcp-yahoo

services:
  yahfinance:
    image: ${DOCKERHUB_NAMESPACE}/finance-mcp-yahoo:${IMAGE_TAG}
    restart: unless-stopped
    env_file:
      - .env.aws-dev
    networks:
      starterp-shared:
        aliases:
          - yahfinance

networks:
  starterp-shared:
    external: true
    name: starterp-shared
