name: yahoo-finance-mcp-aws-dev

services:
  yahfinance:
    image: ${ECR_REGISTRY}/startfinance-v2-dev-yahoo-finance-mcp-ecr:${IMAGE_TAG}
    restart: unless-stopped
    env_file:
      - .env.aws-dev
    networks:
      starterp-shared:
        aliases:
          - yahfinance

networks:
  starterp-shared:
    external: true
    name: starterp-shared
